[pytest]
# 1. Automatic Allure generation
addopts = --alluredir=allure-results --clean-alluredir

# 2. Performance & discovery
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 3. Isolation (Crucial for GitLab Runner on Windows)
# This prevents pytest from trying to read files in the 'builds' or '.venv' folders
norecursedirs = builds .venv .git allure-results allure-report public

# 4. Live Logging (Helpful for debugging long CI runs)
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S